### ISSUE TITLE
Homepage failed to load

### ISSUE THREAD

**Issue by skyusuf15** [Ahmzyjazzy/theatre-event-ticket#1]
The first page of the app seems not to be working.
check the the screenshots below
![screenshot from 2018-04-15 20-46-27](https://user-images.githubusercontent.com/16038049/38783357-c0ba66b4-40f8-11e8-9373-84815f77f71f.png)
![screenshot from 2018-04-15 20-46-21](https://user-images.githubusercontent.com/16038049/38783411-9d8ebed2-40f9-11e8-96ee-baab0fef01f1.png)

**Comment by Ahmzyjazzy** [comment]
@skyusuf15 I cloned and tested same copy and it works fine on my machine. Can you provide a detail, if there is an error message log on apache_error file.

**index**
![image](https://user-images.githubusercontent.com/24432247/38799323-13f30530-415c-11e8-9d1d-eabbb4b6fddb.png)

**login**
![image](https://user-images.githubusercontent.com/24432247/38799448-70f34182-415c-11e8-9012-955b35533948.png)

**Comment by skyusuf15** [comment]
Here is my apache log
![screenshot from 2018-04-20 16-13-25](https://user-images.githubusercontent.com/16038049/39059273-f5d6b7c4-44b5-11e8-958a-a78011767fd8.png)

**Comment by Ahmzyjazzy** [comment]
**mysql** extension was deprecated in PHP 5.5.0, and it was removed in PHP 7.0.0. 
My current php version is 5.4.3 and I guessed that's why it works for me.  Try using the **mysqli** extension. You can replace all mysql with mysqli in the database.php file. This should work.  Thanks.

**Comment by skyusuf15** [comment]
True mysql wont work with php7, i have change to mysqli and it works now. I will suggest you have the mysqli version too or i can push my change to the repo if am allowed.
